SET FOREIGN_KEY_CHECKS=0;

-- DS_COMMON_USER表下面有表(DS_COMMON_USERORG)依赖，删除时要注意

-- DROP TABLE IF EXISTS DS_COMMON_USERORG;
-- DROP TABLE IF EXISTS DS_COMMON_ORGROLE;
-- DROP TABLE IF EXISTS DS_COMMON_ORG;
-- DROP TABLE IF EXISTS DS_COMMON_ROLEFUNC;
-- DROP TABLE IF EXISTS DS_COMMON_ROLE;
-- DROP TABLE IF EXISTS DS_COMMON_FUNC;
-- DROP TABLE IF EXISTS DS_COMMON_SYSTEM;
-- DROP TABLE IF EXISTS DS_COMMON_USER;
-- DROP TABLE IF EXISTS DS_COMMON_USERTYPE;
DROP TABLE IF EXISTS DS_COMMON_LOGIN;



CREATE TABLE IF NOT EXISTS DS_COMMON_LOGIN
(
   ID                   BIGINT NOT NULL COMMENT '主键',
   LOGINTIME            VARCHAR(19) COMMENT '登录时间',
   LOGOUTTIME           VARCHAR(19) COMMENT '登出时间',
   TIMEOUTTIME          VARCHAR(19) COMMENT '超时时间',
   PWDTIME              VARCHAR(19) COMMENT '密码修改时间，没修改则为空，修改成功后直接登出',
   TICKET               VARCHAR(128) COMMENT '登录标识',
   IP                   VARCHAR(128) COMMENT 'IP地址',
   ACCOUNT              VARCHAR(64) COMMENT '操作人账号',
   NAME                 VARCHAR(30) COMMENT '操作人名称',
   STATUS               INT COMMENT '状态(0失败,1成功)',
   PRIMARY KEY (ID)
) COMMENT '系统登录日志';
CREATE TABLE IF NOT EXISTS DS_COMMON_USERTYPE
(
   ID                   BIGINT NOT NULL COMMENT '主键',
   NAME                 VARCHAR(300) COMMENT '名称',
   ALIAS                VARCHAR(300) COMMENT '标识',
   STATUS               INT(1) COMMENT '状态(1)',
   SEQ                  BIGINT(18) COMMENT '排序',
   MEMO                 VARCHAR(1000) COMMENT '扩展信息',
   RESOURCES            VARCHAR(4000) COMMENT '资源集合',
   PRIMARY KEY (ID)
) COMMENT '用户类型';
CREATE TABLE IF NOT EXISTS DS_COMMON_USER
(
   ID                   BIGINT(18) NOT NULL COMMENT '主键',
   ACCOUNT              VARCHAR(64) NOT NULL COMMENT '帐号',
   PASSWORD             VARCHAR(256) COMMENT '密码',
   NAME                 VARCHAR(30) COMMENT '姓名',
   IDCARD               VARCHAR(64) COMMENT '身份证号',
   STATUS               INT(1) COMMENT '状态(1启用,0禁用)',
   EMAIL                VARCHAR(300) COMMENT '电子邮件',
   MOBILE               VARCHAR(30) COMMENT '手机',
   PHONE                VARCHAR(30) COMMENT '电话',
   WORKCARD             VARCHAR(64) COMMENT '工作证号',
   CAKEY                VARCHAR(1024) COMMENT 'CA证书的KEY',
   CREATETIME           VARCHAR(19) COMMENT '创建时间',
   ORGPID               BIGINT(18) COMMENT '所属单位',
   ORGID                BIGINT(18) COMMENT '所属部门',
   TYPE                 VARCHAR(300) COMMENT '类型	',
   TYPENAME             VARCHAR(300) COMMENT '类型名称',
   EXALIAS              VARCHAR(300) COMMENT '类型扩展标识',
   EXNAME               VARCHAR(300) COMMENT '类型扩展名称',
   PRIMARY KEY (ID)
) COMMENT '系统用户';



CREATE TABLE IF NOT EXISTS DS_COMMON_SYSTEM
(
   ID                   BIGINT(18) NOT NULL COMMENT '主键',
   NAME                 VARCHAR(300) COMMENT '名称',
   ALIAS                VARCHAR(128) COMMENT '系统别名',
   PASSWORD             VARCHAR(64) COMMENT '访问密码',
   DOMAINURL            VARCHAR(300) COMMENT '网络地址和端口',
   ROOTURL              VARCHAR(300) COMMENT '应用根路径',
   MENUURL              VARCHAR(300) COMMENT '菜单地址',
   STATUS               INT(1) COMMENT '状态(1启用,0禁用)',
   SEQ                  BIGINT(18) COMMENT '排序',
   MEMO                 VARCHAR(300) COMMENT '备注',
   PRIMARY KEY (ID)
) COMMENT '应用系统';
CREATE TABLE IF NOT EXISTS DS_COMMON_FUNC
(
   ID                   BIGINT(18) NOT NULL COMMENT '主键',
   PID                  BIGINT(18) COMMENT '上级ID(本表)',
   SYSTEMID             BIGINT(18) COMMENT '所属系统ID',
   NAME                 VARCHAR(300) COMMENT '名称',
   ALIAS                VARCHAR(300) COMMENT '标识',
   URI                  VARCHAR(300) COMMENT '对应的URI',
   IMG                  VARCHAR(100) COMMENT '显示图标',
   STATUS               INT(1) COMMENT '状态(0不是菜单,1菜单,不是菜单不能添加下级)',
   SEQ                  BIGINT(18) COMMENT '排序',
   MEMO                 VARCHAR(3000) COMMENT '扩展信息',
   RESOURCES            VARCHAR(4000) COMMENT '资源集合',
   PRIMARY KEY (ID),
   CONSTRAINT FK_DS_COMMON_FUNC_SYSTEM FOREIGN KEY (SYSTEMID)
      REFERENCES DS_COMMON_SYSTEM (ID) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FK_DS_COMMON_FUNC FOREIGN KEY (PID)
      REFERENCES DS_COMMON_FUNC (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT '功能';
CREATE TABLE IF NOT EXISTS DS_COMMON_ROLE
(
   ID                   BIGINT(18) NOT NULL COMMENT '主键',
   PID                  BIGINT(18) COMMENT '上级ID(本表)',
   SYSTEMID             BIGINT(18) NOT NULL COMMENT '所属系统ID',
   NAME                 VARCHAR(300) COMMENT '名称',
   SEQ                  BIGINT(18) COMMENT '排序',
   MEMO                 VARCHAR(300) COMMENT '备注',
   PRIMARY KEY (ID),
   CONSTRAINT FK_DS_COMMON_ROLE_SYSTEM FOREIGN KEY (SYSTEMID)
      REFERENCES DS_COMMON_SYSTEM (ID) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FK_DS_COMMON_ROLE FOREIGN KEY (PID)
      REFERENCES DS_COMMON_ROLE (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT '角色';
CREATE TABLE IF NOT EXISTS DS_COMMON_ROLEFUNC
(
   ID                   BIGINT(18) NOT NULL COMMENT '主键ID',
   SYSTEMID             BIGINT(18) COMMENT '系统ID',
   ROLEID               BIGINT(18) COMMENT '角色ID',
   FUNCID               BIGINT(18) COMMENT '功能ID',
   PRIMARY KEY (ID),
   CONSTRAINT FK_DS_COMMON_ROLEFUNC_SYSTEM FOREIGN KEY (SYSTEMID)
      REFERENCES DS_COMMON_SYSTEM (ID) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FK_DS_COMMON_ROLEFUNC_FUNC FOREIGN KEY (FUNCID)
      REFERENCES DS_COMMON_FUNC (ID) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FK_DS_COMMON_ROLEFUNC_ROLE FOREIGN KEY (ROLEID)
      REFERENCES DS_COMMON_ROLE (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT '角色功能关系';



CREATE TABLE IF NOT EXISTS DS_COMMON_ORG
(
   ID                   BIGINT(18) NOT NULL COMMENT '部门ID',
   PID                  BIGINT(18) COMMENT '上级ID(本表)',
   NAME                 VARCHAR(300) COMMENT '名称',
   STATUS               INT(1) COMMENT '类型(2单位,1部门,0岗位)',
   SEQ                  BIGINT(18) COMMENT '排序',
   DUTYSCOPE            VARCHAR(3000) COMMENT '职责范围',
   MEMO                 VARCHAR(3000) COMMENT '备注',
   PRIMARY KEY (ID),
   CONSTRAINT FK_DS_COMMON_ORG FOREIGN KEY (PID)
      REFERENCES DS_COMMON_ORG (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT '组织机构';
CREATE TABLE IF NOT EXISTS DS_COMMON_ORGROLE
(
   ID                   BIGINT(18) NOT NULL COMMENT '主键ID',
   ORGID                BIGINT(18) NOT NULL COMMENT '岗位ID',
   ROLEID               BIGINT(18) COMMENT '角色ID',
   PRIMARY KEY (ID),
   CONSTRAINT FK_DS_COMMON_ORGROLE_ORG FOREIGN KEY (ORGID)
      REFERENCES DS_COMMON_ORG (ID) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FK_DS_COMMON_ORGROLE_ROLE FOREIGN KEY (ROLEID)
      REFERENCES DS_COMMON_ROLE (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT '岗位角色关系';
CREATE TABLE IF NOT EXISTS DS_COMMON_USERORG
(
   ID                   BIGINT(18) NOT NULL COMMENT '主键ID',
   ORGID                BIGINT(18) NOT NULL COMMENT '岗位ID',
   USERID               BIGINT(18) COMMENT '用户ID',
   PRIMARY KEY (ID),
   CONSTRAINT FK_DS_COMMON_USERORG_ORG FOREIGN KEY (ORGID)
      REFERENCES DS_COMMON_ORG (ID) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FK_DS_COMMON_USERORG_USER FOREIGN KEY (USERID)
      REFERENCES DS_COMMON_USER (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT '用户岗位关系';


